version: '3.8'

services:
  helpdesk-api:
    build:
      context: ./helpdesk-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./helpdesk-api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - JWT_SECRET=your_jwt_secret_key_change_in_production
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/helpdesk
    depends_on:
      - postgres

  helpdesk-web:
    build:
      context: ./helpdesk-web
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./helpdesk-web:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/v1
    depends_on:
      - kong

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=helpdesk
    volumes:
      - postgres_data:/var/lib/postgresql/data

  kong:
    image: kong:2.8.1-alpine
    environment:
      - KONG_DATABASE=off
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
    ports:
      - "8000:8000"  # Proxy
      - "8001:8001"  # Admin API
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    depends_on:
      - helpdesk-api

volumes:
  postgres_data:
